### ISSUE TITLE
Project goal considering CouchDB and PouchDB

### ISSUE THREAD

**Issue by pekhee** [kurko/ember-sync#28]
What Ember Sync is trying to achieve which haven't been achieved by CouchDB?

Can anyone shed some light on this?

**Comment by kurko** [comment]
First, from PouchDB FAQ,

> Can PouchDb sync with MongoDB/MySQL/my current non-CouchDb database?
>
> No, your backend needs to speak the CouchDB replication protocol. The magic of PouchDB <–> CouchDB sync comes from this design, which in particular requires all documents to be versioned with the _rev marker.

It makes no sense to me that a frontend solution for the offline/online would require constraints on the server. Ember-Sync will simply sync Ember adapters, nothing more than that. You don't need to work on adding stuff to your backend for it to work nor are you forced into using CouchDB on your server (which would make no sense to most apps).

Second, Ember-Sync is designed to work seamlessly with Ember.js. Just that.
