### ISSUE TITLE
Can you please let me know why I can't use EmberSync lib in my project?

### ISSUE THREAD

**Issue by ghost** [kurko/ember-sync#38]
Here is a screenshot which I met when I tried to use EmberSync lib in my project.
- I don't use Ember-cli.
  ![error-1](https://cloud.githubusercontent.com/assets/12614652/7841421/63071832-0451-11e5-8f0b-456e78019bcf.png)

**Comment by kurko** [comment]
So, EmberSync was originally designed to work with ES6 (or `requirejs`), so the instructions all follow that. In your particular situation, you need to include `requirejs` (or anything ES6) and `EmberSync` explicitly.
