### ISSUE TITLE
Look into https://github.com/api-hogs/ember-data-offline

### ISSUE THREAD

**Issue by OpakAlex** [kurko/ember-sync#41]
This lib based on ember-sync idea.

**Comment by Ramblurr** [comment]
Both ember-sync and ember-data-offline seem to be in a quasi unmaintained status.

Does anyone have an opinion on which is the better to adopt and spruce up? With all the changes to Ember 2.x and ember-data 2.x, porting ember-sync could be quite a bit of work.

**Comment by OpakAlex** [comment]
it depends, we don't update our prods for 2.x. But we can help if you have issues.
